#!/bin/bash

# Deploy:
# cd /path/to/this/script
# cp ./configure-apache.sh /opt/lucee/sys/upgrade-in-progress/configure-apache.sh
# chmod +x /opt/lucee/sys/upgrade-in-progress/configure-apache.sh

# Update:
# cat ./configure-apache.sh | sudo tee /opt/lucee/sys/upgrade-in-progress/configure-apache.sh

# Source shared functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/shared-functions.sh"

# Set backup timestamp for this run to keep all backups in the same directory
BACKUP_TS="$(date +%Y-%m-%d-%H%M%S)"

# require root
if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root or with sudo."
	exit 1
fi

SCRIPT_DIR="$(cd -P "$(dirname "$(readlink -f "${BASH_SOURCE[0]:-$0}")")" && pwd)"
. "${SCRIPT_DIR}/ENVIRONMENT.sh"

# preflight: check that required Apache modules are enabled
# mod_proxy, mod_setenvif, mod_headers
# Group by module; detect per environment; emit a single error per missing module

report_missing_module() {
	echo "Error: Required Apache module '$1' is not enabled. Please enable it and try again."
}

# Extract the single ErrorDocument 404 line from a block (strip leading '#' and whitespace)
extract_404_line_from_block() {
	local block="$1"
	if [ -z "$block" ]; then
		return 1
	fi
	echo "$block" | awk -v IGNORECASE=1 '
		/^[\t ]*#?[\t ]*ErrorDocument[\t ]+404[\t ]+/ { line=$0 }
		END {
			if (!length(line)) exit 1
			gsub(/^\s*#\s*/, "", line)
			gsub(/^\s*/, "", line)
			print line
		}
	'
}

# Generate per-site include file with conditional ErrorDocument block
generate_site_404_include() {
	local domain="$1"
	local port="$2"
	local error_block="$3"
	
	# Create site includes directory if it doesn't exist
	mkdir -p "$SITE_INCLUDES_404_DIR"
	
	# Generate include file path
	local include_file="${SITE_INCLUDES_404_DIR}/${domain}-${port}.conf"
	
	# Create the include file with header in new location
	cat > "$include_file" << EOF
# Auto-generated per-site include for ${domain}:${port}
# Generated by $0 on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# This file contains conditional ErrorDocument 404 handling for upgrade mode

<IfDefine !LUCEE_UPGRADE_IN_PROGRESS>
EOF

	# Add ErrorDocument 404 line if it exists
	local error_line
	error_line=$(extract_404_line_from_block "$error_block" || true)
	if [ -n "$error_line" ]; then
		append_with_single_newline $'\t'"$error_line" "$include_file"
	fi
	
	# Add closing sections
	cat >> "$include_file" << EOF
</IfDefine>

<IfDefine LUCEE_UPGRADE_IN_PROGRESS>
	# Set flag to indicate this site has a Lucee 404 handler
	Define LUCEE_SITE_HAS_CF_404
</IfDefine>
EOF
	
	# Normalize whitespace in the generated files
	normalize_conf_whitespace "$include_file"
	
	# Fix permissions for both files
	chmod 644 "$include_file" 2>/dev/null || true
	
	echo "$include_file"
}

# Configure site includes for sites with CF 404 handlers
configure_site_includes() {
	local domain="$1"
	local port="$2"
	local conf_file="$3"
	local docroot="$4"
	local error_404_block="$5"
	local from_htaccess="$6"
	
	# Only generate per-site include file if we have a CF 404 block
	if [ -n "$error_404_block" ]; then
		# Generate the include file with the 404 block
		generate_site_404_include "$domain" "$port" "$error_404_block"
		
		# Comment out original 404s
		backup_file "$conf_file"
		comment_all_404_lines "$conf_file"
		
		if [ "$from_htaccess" = "true" ] && ! grep -qi 'NOTE: ErrorDocument 404 moved' "$docroot/.htaccess"; then
			backup_file "$docroot/.htaccess"
			comment_all_404_lines "$docroot/.htaccess"
		fi
		
		# Add per-site include to vhost
		add_include_404_to_vhost "$conf_file" "$domain" "$port"
	fi
	
	# Ensure detection include is present for all sites
	ensure_include_detect_upgrade_in_vhost "$conf_file" "$domain" "$port"
}

# Check if a per-site include already exists for the given domain and port
has_site_include_file_for_404() {
	local domain="$1"
	local port="$2"
	local include_file="${SITE_INCLUDES_404_DIR}/${domain}-${port}.conf"
	[ -f "$include_file" ]
}

# Add per-site include line to vhost if not already present
add_include_404_to_vhost() {
	local vhost_file="$1"
	local domain_match="$2"
	local port_filter="$3"
	local include_file="${SITE_INCLUDES_404_DIR}/${domain_match}-${port_filter}.conf"
	local include_line="Include ${include_file}"
	
	[ -f "$vhost_file" ] || return 1
	
	# Check if this specific include is already present
	if grep -q "Include ${include_file}" "$vhost_file"; then
		return 0
	fi
	
	# Add the include line before </VirtualHost> in the matching vhost
	local tmp
	tmp=$(mktemp)
	awk -v dom="$domain_match" -v port="$port_filter" -v inc_line="$include_line" '
		BEGIN { inblk=0; match_this=0; blk_port=""; inserted=0 }
		/<VirtualHost[> \t]/ { inblk=1; match_this=0; blk_port=""; if (match($0, /<VirtualHost[^>]*:([0-9]+)/, m)) { blk_port=m[1] } }
		inblk && tolower($0) ~ /^[\t ]*server(name|alias)[\t ]+/ {
			if (dom == "") { match_this=1 }
			else {
				low=$0
				if (tolower(low) ~ /(^|[\t ])[\t ]*server(name|alias)[\t ]+([^#]*)/) {
					names=tolower(substr(low, RSTART+RLENGTH- length(substr(low, RSTART+RLENGTH))+1))
					split(names, a, /[\t ]+/)
					for (j in a) { if (a[j]==tolower(dom)) { match_this=1; break } }
				}
			}
		}
		{
			if ($0 ~ /<\/VirtualHost>/) {
				if (inblk && inserted==0 && (dom=="" || match_this) && (port=="" || blk_port==port)) {
					print "\t" inc_line
					print ""
					inserted=1
				}
				inblk=0; match_this=0
			}
			print $0
		}
	' "$vhost_file" > "$tmp"
	if [ $? -eq 0 ]; then
		# Preserve original permissions before overwriting
		local orig_perms
		orig_perms=$(stat -c %a "$vhost_file" 2>/dev/null || echo "644")
		mv -f "$tmp" "$vhost_file"
		chmod "$orig_perms" "$vhost_file" 2>/dev/null || chmod 644 "$vhost_file"
		return 0
	else
		rm -f "$tmp"
		return 1
	fi
}

# Module check helper (return 0 if enabled, 1 if missing)
check_module() {
	DISPLAY_NAME="$1"   # e.g., mod_proxy
	DEBIAN_NAME="$2"    # e.g., proxy

	if [ "$IS_DEBIAN" = true ]; then
		# Prefer a2query when available
		if command -v a2query >/dev/null 2>&1; then
			if a2query -m "$DEBIAN_NAME" 2>/dev/null | grep -qi "enabled"; then
				return 0
			else
				return 1
			fi
		else
			# Fallback to control command module list
			if command -v apache2ctl >/dev/null 2>&1; then
				CTL=apache2ctl
			elif command -v apachectl >/dev/null 2>&1; then
				CTL=apachectl
			else
				return 1
			fi
			if "$CTL" -M 2>/dev/null | grep -q "${DEBIAN_NAME}_module"; then
				return 0
			else
				return 1
			fi
		fi
	elif [ "$IS_CPANEL" = true ]; then
		if /usr/local/cpanel/bin/check_cpanel_module_status --module="$DISPLAY_NAME" | grep -q "^${DISPLAY_NAME}: enabled"; then
			return 0
		else
			return 1
		fi
	elif [ -n "$CONF_DIR" ]; then
		# Fedora, Red Hat, AlmaLinux, Rocky Linux, etc
		if apachectl -M | grep -q "${DEBIAN_NAME}_module"; then
			return 0
		else
			return 1
		fi
	fi

	# Unsupported / not detected
	return 1
}

# Run checks, collect and report
HAS_ERRORS=false

if ! check_module "mod_proxy" "proxy"; then
	report_missing_module "mod_proxy"
	HAS_ERRORS=true
fi

if ! check_module "mod_setenvif" "setenvif"; then
	report_missing_module "mod_setenvif"
	HAS_ERRORS=true
fi

if ! check_module "mod_headers" "headers"; then
	report_missing_module "mod_headers"
	HAS_ERRORS=true
fi

# mod_rewrite is required for conditional proxying during upgrade for allowlisted IPs
if ! check_module "mod_rewrite" "rewrite"; then
	report_missing_module "mod_rewrite"
	HAS_ERRORS=true
fi

if [ "$HAS_ERRORS" = true ]; then
	exit 1
fi

# preflight: required files must exist at /opt path used by per-site Includes and docroot copy
DETECT_CONF="${UPG_DIR}/lucee-detect-upgrade.conf"
UPG_HTML="${UPG_DIR}/lucee-upgrade-in-progress.html"
if [ ! -f "$DETECT_CONF" ]; then
	echo "Error: Required include not found: $DETECT_CONF"
	echo "Run deploy-to-opt-lucee-sys.sh to deploy the package, then retry."
	exit 1
fi
if [ ! -f "$UPG_HTML" ]; then
	echo "Error: Required HTML not found: $UPG_HTML"
	echo "Run deploy-to-opt-lucee-sys.sh to deploy the package, then retry."
	exit 1
fi

# Use [.] instead of \. to avoid awk treating "\." as an escape in string constants
LUCEE404_REGEX='^[[:space:]]*ErrorDocument[[:space:]]+404[[:space:]]+/[^[:space:]]*[.](cfm|cfml|cfc|cfs)([^[:alnum:]_]|$)'
# Any ErrorDocument 404 (any target), for precedence checks and comment-all behavior
ANY404_REGEX='^[[:space:]]*ErrorDocument[[:space:]]+404[[:space:]]+'

if [ ! -f "$SITES_FILE" ]; then
	echo "Lucee sites data file not found."
	echo ""
	echo "Press Enter to get data ..."
	read -r _
	${SUDO} "${UPG_DIR}/get-lucee-sites.sh"
	# Re-check for generated file
	if [ ! -f "$SITES_FILE" ]; then
		echo "Error: Failed to generate sites data file. Aborting now."
		exit 1
	fi
	clear
fi

# cPanel userdata paths (IS_CPANEL provided by ENVIRONMENT.sh)
if [ "$IS_CPANEL" = true ]; then
	CPANEL_USERDATA_SSL_PATH="${CONF_DIR}/userdata/ssl/2_4"
	CPANEL_USERDATA_STD_PATH="${CONF_DIR}/userdata/std/2_4"
fi

# Apache config test helper: uses APACHE_CONTROLLER from ENVIRONMENT.sh
apache_config_test() {
	echo ""
	echo "Testing Apache configuration ..."
	echo ""
	case "$APACHE_CONTROLLER" in
		apache2)
			apache2ctl -t
			;;
		httpd)
			httpd -t
			;;
		apachectl)
			apachectl -t
			;;
		apache2ctl)
			apache2ctl -t
			;;
		*)
			echo "Warning: No apache control binary found for config test; skipping syntax check."
			;;
	esac
}

# Extract the last matching ErrorDocument 404 *.cf* even if it is commented (e.g., from prior runs)
# Strips leading '# ' from the extracted lines and excludes our NOTE lines
extract_404_block_allow_commented() {
	local file="$1"
	[ -f "$file" ] || return 1
	awk -v IGNORECASE=1 -v pat="$LUCEE404_REGEX" '
		{ lines[++n]=$0 }
		# match active or commented ErrorDocument 404 *.cf*
		$0 ~ /^[\t ]*#?[\t ]*ErrorDocument[\t ]+404[\t ]+/ && $0 ~ pat { ln=n }
		END {
			if (!ln) exit 1
			start=ln-1
			while (start>=1 && (lines[start] ~ /^[\t ]*#/ || lines[start] ~ /^[\t ]*$/)) start--
			for (i=start+1; i<ln; i++) {
				if (lines[i] ~ /NOTE: ErrorDocument 404/) continue
				# strip leading comment markers
				sub(/^[\t ]*#[\t ]?/, "", lines[i])
				print lines[i]
			}
			line=lines[ln]
			sub(/^[\t ]*#[\t ]?/, "", line)
			print line
		}
	' "$file"
}

# Return 0 if the last ErrorDocument 404 in file targets .cf*, else return 1
last_404_is_cf() {
	local file="$1"
	[ -f "$file" ] || return 1
	awk -v IGNORECASE=1 '
		/^[\t ]*#/ { next }
		# capture last ErrorDocument 404 target (rest of line after the code)
		match($0, /^[\t ]*ErrorDocument[\t ]+404[\t ]+(.*)$/, m) { last=m[1] }
		END {
			if (!length(last)) exit 1
			# consider it CF only if it ends with .cfm/.cfml/.cfc/.cfs (optionally followed by non-word chars)
			if (last ~ /\.(cfm|cfml|cfc|cfs)([^[:alnum:]_]|$)/) exit 0; else exit 1
		}
	' "$file"
}

# Comment out ALL ErrorDocument 404 lines (any target) with an explanatory note
comment_all_404_lines() {
	local file="$1"
	[ -f "$file" ] || return 0
	local tmp base
	# Preserve ownership and mode (important for user-owned .htaccess)
	local _uid _gid _mode
	_uid=$(stat -c '%u' "$file" 2>/dev/null || echo "")
	_gid=$(stat -c '%g' "$file" 2>/dev/null || echo "")
	_mode=$(stat -c '%a' "$file" 2>/dev/null || echo "")
	tmp=$(mktemp)
	base=$(basename "$file")
	if [ "$base" = ".htaccess" ]; then
		awk -v IGNORECASE=1 -v pat="$ANY404_REGEX" -v note="# NOTE: ErrorDocument 404 moved by /opt/lucee/sys/upgrade-in-progress/configure-apache.sh into Apache vhost/userdata and disabled during upgrades. See per-site Include to /opt/lucee/sys/upgrade-in-progress/lucee-detect-upgrade.conf" '
			{ lines[++n]=$0 }
			END {
				for (i=1;i<=n;i++) {
					if (lines[i] ~ pat) {
						print note
						if (lines[i] ~ /^[\t ]*#/) { print lines[i] }
						else { print "# " lines[i] }
					}
					else { print lines[i] }
				}
			}
		' "$file" > "$tmp"
	else
		awk -v IGNORECASE=1 -v pat="$ANY404_REGEX" -v note="# NOTE: ErrorDocument 404 disabled/commented by /opt/lucee/sys/upgrade-in-progress/configure-apache.sh (managed inline and wrapped in vhost/userdata)." '
			{ lines[++n]=$0 }
			END {
				for (i=1;i<=n;i++) {
					if (lines[i] ~ pat) {
						print note
						if (lines[i] ~ /^[\t ]*#/) { print lines[i] }
						else { print "# " lines[i] }
					}
					else { print lines[i] }
				}
			}
		' "$file" > "$tmp"
	fi
	# Write back in place to preserve existing mode/ownership
	cat "$tmp" > "$file"
	rm -f "$tmp"
	# Restore ownership/mode if we could read them (chown/chmod may fail for non-root; ignore errors)
	if [ -n "$_uid" ] && [ -n "$_gid" ]; then
		chown "$_uid:$_gid" "$file" 2>/dev/null || true
	fi
	if [ -n "$_mode" ]; then
		chmod "$_mode" "$file" 2>/dev/null || true
	fi
}

# Extract the first matching ErrorDocument 404 *.cf* line and its contiguous preceding comments
# Prints the block to stdout; returns non-zero if not found
extract_404_block() {
	local file="$1"
	[ -f "$file" ] || return 1
	awk -v IGNORECASE=1 -v pat="$LUCEE404_REGEX" '
		{ lines[++n]=$0 }
		$0 ~ pat { ln=n }
		END {
			if (!ln) exit 1
			start=ln-1
			while (start>=1 && (lines[start] ~ /^[\t ]*#/ || lines[start] ~ /^[\t ]*$/)) start--
			for (i=start+1; i<ln; i++) print lines[i]
			print lines[ln]
		}
	' "$file"
}

# Remove the first matching ErrorDocument 404 *.cf* line and its contiguous preceding comments from file (in-place)
remove_404_block() {
	local file="$1"
	[ -f "$file" ] || return 0
	local tmp
	tmp=$(mktemp)
	local base
	base=$(basename "$file")
	if [ "$base" = ".htaccess" ]; then
		# In .htaccess: comment out ALL ErrorDocument 404 lines with a note; migration uses the last via extract_404_block()
		awk -v IGNORECASE=1 -v pat="$LUCEE404_REGEX" -v note="# NOTE: ErrorDocument 404 moved by /opt/lucee/sys/upgrade-in-progress/configure-apache.sh into Apache vhost/userdata and disabled during upgrades. See per-site Include to /opt/lucee/sys/upgrade-in-progress/lucee-detect-upgrade.conf" '
			{ lines[++n]=$0 }
			END {
				for (i=1;i<=n;i++) {
					if (lines[i] ~ pat) {
						print note
						if (lines[i] ~ /^[\t ]*#/) {
							print lines[i]
						}
						else {
							print "# " lines[i]
						}
					}
					else {
						print lines[i]
					}
				}
			}
		' "$file" > "$tmp"
	else
		# In vhost/userdata files: comment out ALL ErrorDocument 404 lines with a note
		awk -v IGNORECASE=1 -v pat="$LUCEE404_REGEX" -v note="# NOTE: ErrorDocument 404 disabled/commented by /opt/lucee/sys/upgrade-in-progress/configure-apache.sh (managed inline and wrapped in vhost/userdata)." '
			{ lines[++n]=$0 }
			END {
				for (i=1;i<=n;i++) {
					if (lines[i] ~ pat) {
						print note
						if (lines[i] ~ /^[\t ]*#/) {
							print lines[i]
						}
						else {
							print "# " lines[i]
						}
					}
					else {
						print lines[i]
					}
				}
			}
		' "$file" > "$tmp"
	fi
	if [ $? -eq 0 ]; then
		mv -f "$tmp" "$file"
	else
		rm -f "$tmp"
		return 1
	fi
}

# Ensure the lucee-detect-upgrade.conf Include line exists inside the targeted vhost (by domain and optional port).
ensure_include_detect_upgrade_in_vhost() {
	local vhost_file="$1"
	local domain_match="$2"
	local port_filter="$3"
	local tmp
	# Use the deployed upgrade directory path (absolute) for the Include line
	local include_path="${UPG_DIR}/lucee-detect-upgrade.conf"
	local include_line="Include ${include_path}"
	[ -f "$vhost_file" ] || return 1
	tmp=$(mktemp)
	awk -v dom="$domain_match" -v port="$port_filter" -v inc_line="$include_line" -v inc_path="$include_path" '
		BEGIN { inblk=0; match_this=0; blk_port=""; inserted=0; had_inc=0 }
		{ line=$0; lines[++n]=$0 }
		/<VirtualHost[> \t]/ { inblk=1; match_this=0; blk_port=""; had_inc=0; if (match($0, /<VirtualHost[^>]*:([0-9]+)/, m)) { blk_port=m[1] } }
		inblk && tolower($0) ~ /^[\t ]*server(name|alias)[\t ]+/ {
			if (dom == "") { match_this=1 }
			else {
				low=$0
				if (tolower(low) ~ /(^|[\t ])[\t ]*server(name|alias)[\t ]+([^#]*)/) {
					names=tolower(substr(low, RSTART+RLENGTH- length(substr(low, RSTART+RLENGTH))+1))
					split(names, a, /[\t ]+/)
					for (j in a) { if (a[j]==tolower(dom)) { match_this=1; break } }
				}
			}
		}
		# Detect an existing Include for this exact path inside the current vhost block
		inblk && match($0, /^[\t ]*Include(Optional)?[\t ]+([^ \t#]+)([ \t#]|$)/, m) {
			if (m[2] == inc_path) { had_inc=1 }
		}
		{
			if ($0 ~ /<\/VirtualHost>/) {
				if (inblk && inserted==0 && (dom=="" || match_this) && (port=="" || blk_port==port) && had_inc==0) {
					print "\t" inc_line
					print ""
					inserted=1
				}
				inblk=0; match_this=0; had_inc=0
			}
			print $0
		}
	' "$vhost_file" > "$tmp"
	if [ $? -eq 0 ]; then
		# Preserve original permissions before overwriting
		local orig_perms
		orig_perms=$(stat -c %a "$vhost_file" 2>/dev/null || echo "644")
		mv -f "$tmp" "$vhost_file"
		chmod "$orig_perms" "$vhost_file" 2>/dev/null || chmod 644 "$vhost_file"
	else
		rm -f "$tmp"
		return 1
	fi
}

# Check if mod_headers is enabled (needed for X-Lucee-Upgrade header polling)
# Uses APACHE_CONTROLLER from ENVIRONMENT.sh
headers_module_enabled() {
	case "$APACHE_CONTROLLER" in
		apache2)
			apache2ctl -M 2>/dev/null | grep -qiE '(^|[^[:alnum:]_])headers_module([^[:alnum:]_]|$)'
			return $?
			;;
		httpd)
			httpd -M 2>/dev/null | grep -qiE '(^|[^[:alnum:]_])headers_module([^[:alnum:]_]|$)'
			return $?
			;;
		apachectl)
			apachectl -M 2>/dev/null | grep -qiE '(^|[^[:alnum:]_])headers_module([^[:alnum:]_]|$)'
			return $?
			;;
		apache2ctl)
			apache2ctl -M 2>/dev/null | grep -qiE '(^|[^[:alnum:]_])headers_module([^[:alnum:]_]|$)'
			return $?
			;;
		*)
			# If we can't detect, do not block; treat as enabled to avoid false alarms
			return 0
			;;
	esac
}

find_active_lucee_proxy_conf_path() {
	local path=""
	if [ "$IS_DEBIAN" = true ]; then
		if [ -f "/etc/apache2/conf-available/lucee-proxy.conf" ]; then
			path="/etc/apache2/conf-available/lucee-proxy.conf"
		else
			path=$(find /etc/apache2 -maxdepth 2 -type f -name "lucee-proxy.conf" 2>/dev/null | head -1)
		fi
	elif [ -n "$CONF_DIR" ]; then
		if [ -f "${CONF_DIR}/lucee-proxy.conf" ]; then
			path="${CONF_DIR}/lucee-proxy.conf"
		else
			path=$(find "$CONF_DIR" -maxdepth 1 -type f -name "lucee-proxy*.conf" 2>/dev/null | head -1)
		fi
	fi
	if [ -n "$path" ] && [ -f "$path" ]; then
		echo "$path"
		return 0
	fi
	echo ""
	return 1
}

generate_allowed_ip_proxy_include() {

	# Generates internal mapping plus rewrite-gated access for allowlisted IPs
	# Summary:
	# - '/.lucee-upgrade-proxy/' is an internal URI used only as a bridge
	#   between mod_rewrite and mod_proxy.
	# - Apache forbids ProxyPass/ProxyPassMatch inside conditional blocks,
	#   so we always define a ProxyPassMatch for that internal path,
	#   then rewrite allowed client requests to it when LUCEE_UPGRADE_BYPASS=1.
	# - This allows allowlisted IPs to reach Lucee normally while non-allowed
	#   IPs are served lucee-upgrade-in-progress.html.
	# - For AJP backends, we extract and propagate 'secret=...' to keep
	#   upgrade-mode proxying secure.
	
	local src
	src=$(find_active_lucee_proxy_conf_path)
	if [ -z "$src" ]; then
		echo "Error: Could not find active lucee-proxy.conf on this system."
		echo "Ensure your Lucee proxy config exists (e.g., /etc/apache2/conf-available/lucee-proxy.conf or ${CONF_DIR}/lucee-proxy.conf)."
		return 1
	fi

	local content
	content=$(cat "$src")
	if [ -z "$content" ]; then
		echo "Error: Active lucee-proxy.conf at $src is empty."
		return 1
	fi

	local dest="${UPG_DIR}/lucee-proxy-for-allowed-ip.conf"
	local tmp
	tmp=$(mktemp)

	# Derive backend target from the active lucee-proxy.conf
	# Prefer balancer://, then ajp://, then http(s)://; fallback to http://127.0.0.1:8888
	local backend_url
	local backend_type
	local ppm_line
	backend_url=""
	backend_type=""
	ppm_line=""
	# balancer
	if echo "$content" | grep -Eiq "^[[:space:]]*ProxyPassMatch[[:space:]].*balancer://"; then
		backend_url=$(echo "$content" | awk '/^[\t ]*ProxyPassMatch[\t ]/ { for (i=1;i<=NF;i++) if ($i ~ /^balancer:\/\//) { print $i; exit } }')
		ppm_line=$(echo "$content" | awk '/^[\t ]*ProxyPassMatch[\t ]/ { for (i=1;i<=NF;i++) if ($i ~ /^balancer:\/\//) { print $0; exit } }')
		if [ -n "$backend_url" ]; then
			backend_type="balancer"
		fi
	fi
	# ajp
	if [ -z "$backend_url" ] && echo "$content" | grep -Eiq "^[[:space:]]*ProxyPassMatch[[:space:]].*ajp://"; then
		backend_url=$(echo "$content" | awk '/^[\t ]*ProxyPassMatch[\t ]/ { for (i=1;i<=NF;i++) if ($i ~ /^ajp:\/\//) { print $i; exit } }')
		ppm_line=$(echo "$content" | awk '/^[\t ]*ProxyPassMatch[\t ]/ { for (i=1;i<=NF;i++) if ($i ~ /^ajp:\/\//) { print $0; exit } }')
		if [ -n "$backend_url" ]; then
			backend_type="ajp"
		fi
	fi
	# http/https
	if [ -z "$backend_url" ] && echo "$content" | grep -Eiq "^[[:space:]]*ProxyPassMatch[[:space:]].*https?://"; then
		backend_url=$(echo "$content" | awk '/^[\t ]*ProxyPassMatch[\t ]/ { for (i=1;i<=NF;i++) if ($i ~ /^https?:\/\//) { print $i; exit } }')
		ppm_line=$(echo "$content" | awk '/^[\t ]*ProxyPassMatch[\t ]/ { for (i=1;i<=NF;i++) if ($i ~ /^https?:\/\//) { print $0; exit } }')
		if [ -n "$backend_url" ]; then
			backend_type="http"
		fi
	fi
	# fallback
	if [ -z "$backend_url" ]; then
		backend_url="http://127.0.0.1:8888"
		backend_type="http"
	fi

	# Normalize: strip any trailing '/$1$2' (with optional trailing '/') carried over from ProxyPassMatch
	backend_url=$(echo "$backend_url" | sed -E 's#/\$1\$2/?$##')

	# Extract options that follow the backend URL in the selected ProxyPassMatch line
	# Preserve all flags and key=value pairs (e.g., nocanon, keepalive=On, secret=...)
	local ppm_opts
	ppm_opts=""
	if [ -n "$ppm_line" ]; then
		ppm_opts=$(echo "$ppm_line" | awk '
			BEGIN { idx=0 }
			{
				for (i=1; i<=NF; i++) {
					if ($i ~ /^(balancer|ajp|https?):\/\//) { idx=i; break }
				}
				if (idx>0 && idx<NF) {
					for (k=idx+1; k<=NF; k++) {
						printf " %s", $k
					}
				}
			}
		')
	fi

	# Warn if AJP secret is missing on the selected ProxyPassMatch line
	if [ "$backend_type" = "ajp" ] && ! echo "$ppm_opts" | grep -Eq '(^|[[:space:]])secret='; then
		echo "Warning: AJP backend detected but no 'secret=' option found on ProxyPassMatch line in $src."
	fi

	{
		echo "# Auto-generated by ${UPG_DIR}/configure-apache.sh"
		echo "# Source: $src"
		echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
		echo "# Conditional proxy for allowlisted IPs only"
		echo ""
		echo "# Internal upgrade proxy mapping (not directly reachable unless rewritten)"
		# Use printf to correctly emit literal $1 and $2 backrefs without stray escapes
		printf 'ProxyPassMatch ^/\\.lucee-upgrade-proxy/(.+\\.(?:cfm|cfml|cfc|cfs))(.*)$ %s/$1$2%s\n' "${backend_url}" "${ppm_opts}"
		printf 'ProxyPassReverse /.lucee-upgrade-proxy/ %s/\n' "${backend_url}"
		echo "<IfModule mod_rewrite.c>"
		# Use printf (single-quoted) to avoid shell expansion of $1/$2 backrefs
		printf '\tRewriteEngine On\n'
		printf '\t# Allow Lucee access only for IPs flagged via LUCEE_UPGRADE_BYPASS\n'
		printf '\tRewriteCond %%{ENV:LUCEE_UPGRADE_BYPASS} =1\n'
		printf '\tRewriteRule ^/(.+\\.(?:cfm|cfml|cfc|cfs))(.*)$ /.lucee-upgrade-proxy/$1$2 [PT,QSA,L]\n'
		echo "</IfModule>"
	} > "$tmp"

	if [ -f "$dest" ]; then
		if cmp -s "$tmp" "$dest"; then
			rm -f "$tmp"
			return 0
		fi
		backup_file "$dest"
	fi
	cp -f "$tmp" "$dest"
	chmod 644 "$dest"
	rm -f "$tmp"
	
	# Normalize whitespace in the generated file
	normalize_conf_whitespace "$dest"
	
	return 0
}


# Detect manually delineated Lucee proxy block in Apache config
# Returns 0 if found, 1 if not found
find_manual_proxy_block() {
	local config_file="$1"
	[ -f "$config_file" ] || return 1
	awk '
		/^[[:space:]]*#[[:space:]]*begin[[:space:]]+[Ll]ucee[[:space:]]+proxy/ { start=NR; next }
		/^[[:space:]]*#[[:space:]]*end[[:space:]]+[Ll]ucee[[:space:]]+proxy/ { 
			if (start) { 
				for (i=start+1; i<NR; i++) print lines[i]
				exit 0 
			}
		}
		{ lines[NR]=$0 }
		END { exit 1 }
	' "$config_file"
}

# Extract Lucee proxy block using regex patterns (fallback method)
# Based on install_mod_proxy.sh patterns
find_regex_proxy_block() {
	local config_file="$1"
	[ -f "$config_file" ] || return 1
	
	# Extract IfModule mod_proxy.c blocks and check for ProxyPassMatch with cf
	local in_block=0
	local block_content=""
	
	while IFS= read -r line; do
		case "$line" in
			*"<IfModule"*"mod_proxy.c>"*)
				in_block=1
				block_content="$line"
				;;
			*"</IfModule>"*)
				if [ "$in_block" = "1" ]; then
					block_content="$block_content"$'\n'"$line"
					# Check if this block contains ProxyPassMatch with cf
					if echo "$block_content" | grep -q "ProxyPassMatch.*cf"; then
						# Output the block as-is with header comment
						echo "# Lucee proxy configuration (migrated from global Apache config)"
						echo "$block_content"
						return 0
					fi
					in_block=0
					block_content=""
				fi
				;;
			*)
				if [ "$in_block" = "1" ]; then
					block_content="$block_content"$'\n'"$line"
				fi
				;;
		esac
	done < "$config_file"
	
	return 1
}

# Find and extract Lucee proxy configuration from global Apache config
# Returns the proxy block content or empty if not found
find_lucee_proxy_block() {
	local config_file="$1"
	[ -f "$config_file" ] || return 1
	
	# Try manual delineation first
	local proxy_block
	proxy_block=$(find_manual_proxy_block "$config_file" 2>/dev/null)
	if [ $? -eq 0 ] && [ -n "$proxy_block" ]; then
		echo "$proxy_block"
		return 0
	fi
	
	# Fallback to regex detection
	proxy_block=$(find_regex_proxy_block "$config_file" 2>/dev/null)
	if [ $? -eq 0 ] && [ -n "$proxy_block" ]; then
		echo "$proxy_block"
		return 0
	fi
	
	return 1
}

# Replace Lucee proxy block with comment indicating migration
# Returns 0 on success, 1 on failure
replace_proxy_with_comment() {
	local config_file="$1"
	local proxy_conf_path="$2"
	[ -f "$config_file" ] || return 1
	
	local tmp
	tmp=$(mktemp)
	
	# Try manual delineation replacement first
	if awk -v conf="$proxy_conf_path" '
		/^[[:space:]]*#[[:space:]]*begin[[:space:]]+[Ll]ucee[[:space:]]+proxy/ { 
			print "# Lucee proxy configuration moved to " conf
			comment_mode=1; next 
		}
		/^[[:space:]]*#[[:space:]]*end[[:space:]]+[Ll]ucee[[:space:]]+proxy/ { 
			if (comment_mode) { comment_mode=0; next }
		}
		comment_mode { print "# " $0; next }
		{ print }
	' "$config_file" > "$tmp"; then
		# Check if replacement actually happened
		if ! cmp -s "$config_file" "$tmp"; then
			# Preserve original permissions before overwriting
			local orig_perms
			orig_perms=$(stat -c %a "$config_file" 2>/dev/null || echo "644")
			mv "$tmp" "$config_file"
			chmod "$orig_perms" "$config_file" 2>/dev/null || chmod 644 "$config_file"
			# Normalize whitespace to prevent multiple empty lines
			normalize_conf_whitespace "$config_file"
			return 0
		fi
	fi
	
	# Fallback to regex-based replacement - completely rewritten to handle newlines properly
	awk -v conf="$proxy_conf_path" '
		BEGIN { 
			in_proxy=0; 
			replaced=0; 
			proxy_content=""; 
		}
		
		/<IfModule[[:space:]]+mod_proxy\.c>/ {
			if (!replaced) {
				in_proxy=1;
				proxy_start=NR;
				proxy_content=$0;
				next;
			}
		}
		
		in_proxy && /<\/IfModule>/ {
			proxy_content = proxy_content "\n" $0;
			
			# Check if this is a Lucee proxy block
			if (proxy_content ~ /ProxyPassMatch.*cf/) {
				print "# Lucee proxy configuration moved to " conf;
				
				# Split the content into lines and comment each line
				split(proxy_content, lines, "\n");
				for (i = 1; i in lines; i++) {
					if (lines[i] != "") {
						print "# " lines[i];
					}
				}
				replaced=1;
			}
			else {
				# Not a Lucee block, print it as-is
				print proxy_content;
			}
			
			in_proxy=0;
			proxy_content="";
			next;
		}
		
		in_proxy { 
			proxy_content = proxy_content "\n" $0; 
			next; 
		}
		
		{ print; }
	' "$config_file" > "$tmp"
	
	if [ $? -eq 0 ]; then
		# Preserve original permissions before overwriting
		local orig_perms
		orig_perms=$(stat -c %a "$config_file" 2>/dev/null || echo "644")
		mv "$tmp" "$config_file"
		chmod "$orig_perms" "$config_file" 2>/dev/null || chmod 644 "$config_file"
		# Normalize whitespace to prevent multiple empty lines
		normalize_conf_whitespace "$config_file"
		return 0
	else
		rm -f "$tmp"
		return 1
	fi
}

# Migrate existing Lucee proxy config from global Apache to lucee-proxy.conf
# Returns 0 on success, 1 on failure, 2 if no migration needed
migrate_lucee_proxy_config() {
	local global_config_dir="$1"
	local proxy_conf_path="$2"
	
	# Skip if lucee-proxy.conf already exists
	if [ -f "$proxy_conf_path" ]; then
		echo "lucee-proxy.conf already exists; skipping migration"
		return 2
	fi
	
	# Search for Lucee proxy config in global Apache files
	local proxy_block=""
	local source_file=""
	
	# Check common global config files
	for config_file in \
		"$global_config_dir"/includes/*.conf \
		"$global_config_dir"/*.conf \
		"$(dirname "$global_config_dir")"/httpd.conf \
		"$(dirname "$global_config_dir")"/conf/httpd.conf \
		"$(dirname "$global_config_dir")"/apache2.conf
	do
		[ -f "$config_file" ] || continue
		proxy_block=$(find_lucee_proxy_block "$config_file" 2>/dev/null)
		if [ $? -eq 0 ] && [ -n "$proxy_block" ]; then
			source_file="$config_file"
			break
		fi
	done
	
	if [ -z "$proxy_block" ] || [ -z "$source_file" ]; then
		echo "Error: Unable to automatically identify Lucee proxy configuration."
		echo ""
		echo "Please manually delineate your Apache global configuration like this:"
		echo ""
		echo "# begin Lucee proxy"
		echo "[your existing proxy configuration here]"
		echo "# end Lucee proxy"
		echo ""
		echo "Then run this script again."
		exit 1
	fi
	
	echo "Found Lucee proxy configuration in: $source_file"
	echo "Migrating to: $proxy_conf_path"
	
	# Backup source file
	backup_file "$source_file"
	
	# Write proxy block to lucee-proxy.conf
	{
		echo "$proxy_block"
	} > "$proxy_conf_path"
	
	# Normalize whitespace in the generated file
	normalize_conf_whitespace "$proxy_conf_path"
	
	# Replace original block with comment indicating migration
	if replace_proxy_with_comment "$source_file" "$proxy_conf_path"; then
		echo "Successfully migrated Lucee proxy configuration"
		return 0
	else
		echo "Error: Failed to replace proxy block with migration comment"
		return 1
	fi
}

# Ensure global Apache confs exist and are set to normal-state defaults
# Normal state: lucee-proxy enabled; upgrade flag disabled
ensure_global_confs() {
	
	echo ""
	echo "Checking for existing Lucee proxy configuration ..."

	# Debian, Ubuntu, Pop!_OS, etc
	if [ "$IS_DEBIAN" = true ]; then

		# Debian/Ubuntu - check if proxy migration is needed
		conf_avail="/etc/apache2/conf-available"
		if [ ! -f "${conf_avail}/lucee-proxy.conf" ]; then
			# Try to migrate existing proxy config
			migrate_lucee_proxy_config "$conf_avail" "${conf_avail}/lucee-proxy.conf"
		fi

		conf_avail="/etc/apache2/conf-available"
		opt_file="${UPG_DIR}/lucee-upgrade-in-progress.conf"
		if [ -f "$opt_file" ] && [ ! -f "${conf_avail}/lucee-upgrade-in-progress.conf" ]; then
			echo "Installing ${conf_avail}/lucee-upgrade-in-progress.conf ..."
			cp -f "$opt_file" "${conf_avail}/lucee-upgrade-in-progress.conf"
			normalize_conf_whitespace "${conf_avail}/lucee-upgrade-in-progress.conf"
		fi
		# Proxy migration already handled in early check
		# Ensure upgrade flag is disabled by default
		disable_conf lucee-upgrade-in-progress
		# Ensure lucee-proxy.conf is enabled if present in conf-available
		if [ -f "${conf_avail}/lucee-proxy.conf" ]; then
			enable_conf lucee-proxy
		fi
		# Warn if no Lucee proxying detected in global config
		proxy_detected=false
		if [ -f "${conf_avail}/lucee-proxy.conf" ] || [ -f "/etc/apache2/conf-enabled/lucee-proxy.conf" ]; then
			proxy_detected=true
		elif grep -Rqi 'ProxyPassMatch.*cf' /etc/apache2/ 2>/dev/null; then
			proxy_detected=true
		fi
		if [ "$proxy_detected" == true ]; then
			echo "Lucee proxy configuration confirmed"
		else
			echo "Warning: Lucee proxy configuration not detected in global Apache config (Debian/Ubuntu). Normal operation expects mod_proxy enabled."
		fi
		# Warn if mod_headers isn't enabled (needed for HEAD-based polling via X-Lucee-Upgrade)
		if ! headers_module_enabled; then
			echo "Warning: Apache mod_headers does not appear to be enabled."
			echo "The upgrade status page relies on X-Lucee-Upgrade header for HEAD polling."
			echo "Enable with: a2enmod headers && systemctl reload apache2"
		fi
		return
	fi

	# has conf.d (Fedora, Red Hat, AlmaLinux, Rocky Linux, etc)
	if [ -n "$CONF_DIR" ]; then

		# RedHat/CentOS - check if proxy migration is needed
		if [ ! -f "${CONF_DIR}/lucee-proxy.conf" ]; then
			# Try to migrate existing proxy config
			migrate_lucee_proxy_config "$CONF_DIR" "${CONF_DIR}/lucee-proxy.conf"
		fi

		opt_file="${UPG_DIR}/lucee-upgrade-in-progress.conf"
		# Ensure a disabled copy exists if neither form exists
		if [ -f "$opt_file" ] && [ ! -f "${CONF_DIR}/lucee-upgrade-in-progress.disabled" ] && [ ! -f "${CONF_DIR}/lucee-upgrade-in-progress.conf" ]; then
			echo "Installing global lucee-upgrade-in-progress.disabled into ${CONF_DIR}/"
			cp -f "$opt_file" "${CONF_DIR}/lucee-upgrade-in-progress.disabled"
			normalize_conf_whitespace "${CONF_DIR}/lucee-upgrade-in-progress.disabled"
		fi
		# Proxy migration already handled in early check
		# Ensure normal state: upgrade flag disabled
		if [ -f "${CONF_DIR}/lucee-upgrade-in-progress.conf" ]; then
			# Backup existing .disabled if present to avoid clobbering (mirrored under BACKUP_ROOT)
			if [ -f "${CONF_DIR}/lucee-upgrade-in-progress.disabled" ]; then
				echo "Backing up existing ${CONF_DIR}/lucee-upgrade-in-progress.disabled"
				backup_file "${CONF_DIR}/lucee-upgrade-in-progress.disabled"
			fi
			echo "Disabling lucee-upgrade-in-progress.conf (normal state)"
			mv -f "${CONF_DIR}/lucee-upgrade-in-progress.conf" "${CONF_DIR}/lucee-upgrade-in-progress.disabled"
		fi
		# Create lucee-proxy.conf in conf-available
		echo "Creating lucee-proxy.conf ..."
		find_regex_proxy_block > "$CONF_AVAILABLE_DIR/lucee-proxy.conf"
		normalize_conf_whitespace "$CONF_AVAILABLE_DIR/lucee-proxy.conf"
		# Ensure lucee-proxy.conf is enabled (rename from .disabled if needed)
		if [ -f "${CONF_DIR}/lucee-proxy.conf.disabled" ] && [ ! -f "${CONF_DIR}/lucee-proxy.conf" ]; then
			echo "Enabling lucee-proxy.conf (normal state)"
			mv -f "${CONF_DIR}/lucee-proxy.conf.disabled" "${CONF_DIR}/lucee-proxy.conf"
		fi
		# Warn if no Lucee proxying detected in global config
		proxy_detected=false
		if [ -f "${CONF_DIR}/lucee-proxy.conf" ] || [ -f "${CONF_DIR}/lucee-proxy.conf.disabled" ]; then
			proxy_detected=true
		elif grep -Rqi 'ProxyPassMatch.*cf' "${CONF_DIR}" 2>/dev/null; then
			proxy_detected=true
		fi
		if [ "$proxy_detected" == true ]; then
			echo "Lucee proxy configuration confirmed"
		else
			echo "Warning: Lucee proxy configuration not detected in global Apache config (${CONF_DIR}). Normal operation expects mod_proxy enabled."
		fi
		# Warn if mod_headers isn't enabled (needed for HEAD-based polling via X-Lucee-Upgrade)
		if ! headers_module_enabled; then
			echo "Warning: Apache mod_headers does not appear to be enabled."
			echo "The upgrade status page relies on X-Lucee-Upgrade header for HEAD polling."
			echo "Ensure headers_module is loaded (usually enabled by default on RHEL/cPanel)."
		fi
		return
	fi
}

copy_upgrade_html() {
	local docroot=$1
	# Backup existing docroot file (mirrored under BACKUP_ROOT)
	backup_file ${docroot}/lucee-upgrade-in-progress.html
	cp -f "${UPG_DIR}/lucee-upgrade-in-progress.html" ${docroot}/lucee-upgrade-in-progress.html
	
	# Ensure proper ownership - try to match docroot ownership
	if ! chown --reference=${docroot} ${docroot}/lucee-upgrade-in-progress.html 2>/dev/null; then
		echo "Warning: Could not set ownership of ${docroot}/lucee-upgrade-in-progress.html to match docroot"
		
		# Fallback: Try to use Apache user if we can detect it
		local apache_user=""
		if [ "$IS_DEBIAN" = true ]; then
			apache_user="www-data"
		elif [ "$IS_CPANEL" = true ]; then
			apache_user="nobody"
		else
			# Try to detect Apache user on RHEL/CentOS systems
			if [ -n "$CONF_DIR" ] && [ -f "$CONF_DIR/httpd.conf" ]; then
				apache_user=$(grep -i "^User" "$CONF_DIR/httpd.conf" 2>/dev/null | head -1 | awk '{print $2}' || echo "apache")
			else
				apache_user="apache"
			fi
		fi
		
		if [ -n "$apache_user" ]; then
			echo "  Attempting to set ownership to Apache user: $apache_user"
			chown $apache_user ${docroot}/lucee-upgrade-in-progress.html 2>/dev/null || echo "  Failed to set ownership to $apache_user"
		fi
		
		# Ensure the file is at least world-readable as last resort
		chmod 644 ${docroot}/lucee-upgrade-in-progress.html 2>/dev/null || echo "  Warning: Could not ensure ${docroot}/lucee-upgrade-in-progress.html is readable"
	fi
	
	# Handle SELinux context if SELinux is enabled (common on RHEL/CentOS)
	if command -v getenforce >/dev/null 2>&1; then
		if [ "$(getenforce 2>/dev/null)" != "Disabled" ]; then
			echo "  SELinux detected, setting appropriate context"
			
			# Try to match context of an existing HTML file in docroot
			local reference_file
			reference_file=$(find "$docroot" -type f -name "*.html" -o -name "*.htm" | head -1)
			
			if [ -n "$reference_file" ] && [ -f "$reference_file" ]; then
				# Use reference file context
				echo "  Using context from reference file: $reference_file"
				chcon --reference="$reference_file" "${docroot}/lucee-upgrade-in-progress.html" 2>/dev/null || \
					echo "  Failed to set SELinux context from reference file"
			else
				# No reference file, use standard httpd_sys_content_t context
				chcon -t httpd_sys_content_t "${docroot}/lucee-upgrade-in-progress.html" 2>/dev/null || \
					echo "  Failed to set standard httpd_sys_content_t context"
				
				# If restorecon is available, try that as well
				if command -v restorecon >/dev/null 2>&1; then
					restorecon -v "${docroot}/lucee-upgrade-in-progress.html" 2>/dev/null || true
				fi
			fi
		fi
	fi
	
	# Verify the file is readable
	if [ ! -r "${docroot}/lucee-upgrade-in-progress.html" ]; then
		echo "Error: ${docroot}/lucee-upgrade-in-progress.html is not readable. This may cause issues during upgrades."
	fi
	
}

configure_site_debian() {
	local domain=$1
	local docroot=$2
	
	echo ""
	echo "Processing $domain with DocumentRoot: $docroot"
	
	# Copy lucee-upgrade-in-progress.html to DocumentRoot
	copy_upgrade_html "$docroot"
	
	# Check if the SSL site in sites-enabled is a regular file (not a symlink)
	# This would happen if a previous buggy version of the script replaced the symlink
	enabled_ssl_conf="/etc/apache2/sites-enabled/${domain}-ssl.conf"
	if [ -f "$enabled_ssl_conf" ] && [ ! -L "$enabled_ssl_conf" ]; then
		echo "  Found regular file instead of symlink at $enabled_ssl_conf"
		echo "  Restoring symlink structure ..."
		# Backup the unexpected regular file before removal (mirrored under BACKUP_ROOT)
		echo "  Backing up $enabled_ssl_conf"
		backup_file "$enabled_ssl_conf"
		# Get the site name without extension and remove the stray file
		site_name="${domain}-ssl"
		rm -f "$enabled_ssl_conf"
		
		# Enable the site (creates a proper symlink)
		a2ensite "$site_name" > /dev/null 2>&1
		
		echo "  Symlink restored for $site_name"
	fi
	
	# Find the SSL site configuration file in sites-available directly
	ssl_conf_file="/etc/apache2/sites-available/${domain}-ssl.conf"
	if [ ! -f "$ssl_conf_file" ]; then
		# Try to find by ServerName
		ssl_conf_file=$(grep -l "ServerName $domain" /etc/apache2/sites-available/*-ssl.conf 2>/dev/null | head -1)
	fi
	
	local ssl_404_block=""
	if [ -f "$ssl_conf_file" ]; then
		echo "  Updating $ssl_conf_file"
		
		# Check if per-site include already exists
		if has_site_include_file_for_404 "$domain" "443"; then
			echo "  Per-site include already exists for ${domain}:443; ensuring vhost includes it"
			add_include_404_to_vhost "$ssl_conf_file" "$domain" "443"
			ensure_include_detect_upgrade_in_vhost "$ssl_conf_file" "$domain" "443"
		else
			# Extract 404 block for per-site include generation
			local ssl_from_htaccess="false"
			
			# Prefer .htaccess (more specific) over vhost for effective 404
			if [ -f "$docroot/.htaccess" ] && last_404_is_cf "$docroot/.htaccess"; then
				ssl_404_block=$(extract_404_block "$docroot/.htaccess" || true)
				if [ -n "$ssl_404_block" ]; then
					echo "  Using 404 from .htaccess for SSL per-site include"
					ssl_from_htaccess="true"
				fi
			fi
			
			# If .htaccess has already been commented by a prior run, recover the 404 from it
			if [ -z "$ssl_404_block" ] && [ -f "$docroot/.htaccess" ] && grep -qi 'NOTE: ErrorDocument 404 moved' "$docroot/.htaccess"; then
				ssl_404_block=$(extract_404_block_allow_commented "$docroot/.htaccess" || true)
				if [ -n "$ssl_404_block" ]; then
					echo "  Recovered 404 from commented .htaccess for SSL per-site include"
					ssl_from_htaccess="true"
				fi
			fi
			
			# If no .htaccess 404, fallback to local vhost 404
			if [ -z "$ssl_404_block" ]; then
				if last_404_is_cf "$ssl_conf_file"; then
					ssl_404_block=$(extract_404_block "$ssl_conf_file" || true)
					if [ -n "$ssl_404_block" ]; then
						echo "  Using local 404 from SSL vhost for per-site include"
					fi
				fi
			fi
			
			# Generate per-site include file if we have a 404 block
			configure_site_includes "$domain" "443" "$ssl_conf_file" "$docroot" "$ssl_404_block" "$ssl_from_htaccess"
			
			# Ensure detection include is present
			ensure_include_detect_upgrade_in_vhost "$ssl_conf_file" "$domain" "443"
		fi
	else
		echo "  Warning: Could not find SSL configuration file for $domain"
	fi

	# Also update the HTTP (port 80) VirtualHost if present
	# Find the HTTP site configuration file in sites-available
	http_conf_file="/etc/apache2/sites-available/${domain}.conf"
	if [ ! -f "$http_conf_file" ]; then
		# Try to find by ServerName, excluding -ssl.conf
		http_conf_file=$(grep -l "ServerName $domain" /etc/apache2/sites-available/*.conf 2>/dev/null | grep -v -- '-ssl\.conf' | head -1)
	fi

	if [ -f "$http_conf_file" ]; then
		echo "  Updating $http_conf_file"
		
		# Check if per-site include already exists
		if has_site_include_file_for_404 "$domain" "80"; then
			echo "  Per-site include already exists for ${domain}:80; ensuring vhost includes it"
			add_include_404_to_vhost "$http_conf_file" "$domain" "80"
			ensure_include_detect_upgrade_in_vhost "$http_conf_file" "$domain" "80"
		else
			# Extract 404 block for per-site include generation
			local http_404_block=""
			local http_from_htaccess="false"
			
			# If we already have SSL 404 block, reuse it for HTTP
			if [ -n "$ssl_404_block" ]; then
				echo "  Reusing 404 from SSL vhost for HTTP per-site include"
				http_404_block="$ssl_404_block"
			else
				# Extract from .htaccess or vhost as fallback
				if [ -f "$docroot/.htaccess" ] && last_404_is_cf "$docroot/.htaccess"; then
					http_404_block=$(extract_404_block "$docroot/.htaccess" || true)
					if [ -n "$http_404_block" ]; then
						echo "  Using 404 from .htaccess for HTTP per-site include"
						http_from_htaccess="true"
					fi
				fi
				
				# If .htaccess has already been commented by a prior run, recover the 404 from it
				if [ -z "$http_404_block" ] && [ -f "$docroot/.htaccess" ] && grep -qi 'NOTE: ErrorDocument 404 moved' "$docroot/.htaccess"; then
					http_404_block=$(extract_404_block_allow_commented "$docroot/.htaccess" || true)
					if [ -n "$http_404_block" ]; then
						echo "  Recovered 404 from commented .htaccess for HTTP per-site include"
						http_from_htaccess="true"
					fi
				fi
				
				# If no .htaccess 404, fallback to local vhost 404
				if [ -z "$http_404_block" ]; then
					if last_404_is_cf "$http_conf_file"; then
						http_404_block=$(extract_404_block "$http_conf_file" || true)
						if [ -n "$http_404_block" ]; then
							echo "  Using local 404 from HTTP vhost for per-site include"
						fi
					fi
				fi
			fi
			
			# Generate per-site include file if we have a 404 block
			configure_site_includes "$domain" "80" "$http_conf_file" "$docroot" "$http_404_block" "$http_from_htaccess"
			
			# Ensure detection include is present
			ensure_include_detect_upgrade_in_vhost "$http_conf_file" "$domain" "80"
		fi
		# Best-effort warning if HTTP VirtualHost may not redirect to HTTPS
		if ! grep -Eiq '(Redirect(\s+(permanent|temp|301|302))?\s+/?\s+https?://|RewriteRule\s+.*https://)' "$http_conf_file"; then
			echo "  Warning: HTTP vhost for $domain may not redirect to HTTPS. Ensure a proper 80->443 redirect is configured to avoid exposure over HTTP."
		fi
	else
		echo "  Info: No HTTP configuration file found for $domain"
	fi

	# Final normalization: if per-site includes exist and .htaccess still has any 404s, comment them out
	if [ -f "$docroot/.htaccess" ] && grep -qiE "$ANY404_REGEX" "$docroot/.htaccess"; then
		if has_site_include_file_for_404 "$domain" "443" || has_site_include_file_for_404 "$domain" "80"; then
			echo "  Commenting out 404 ErrorDocument in $docroot/.htaccess and adding note"
			backup_file "$docroot/.htaccess"
			comment_all_404_lines "$docroot/.htaccess"
		fi
	fi
}

# Function to configure cPanel sites
configure_site_cpanel() {
	local domain=$1
	local docroot=$2
	
	echo "Processing cPanel site: $domain with DocumentRoot: $docroot"
	
	# expected cPanel docroot: /home/user/public_html
	user=$(echo "$docroot" | awk -F '/' '{print $3}')
	
	# Copy lucee-upgrade-in-progress.html to DocumentRoot
	copy_upgrade_html "$docroot"
	
	# Create userdata directory
	mkdir -p ${CPANEL_USERDATA_SSL_PATH}/${user}/${domain}
	mkdir -p ${CPANEL_USERDATA_STD_PATH}/${user}/${domain}

	# Check if per-site includes already exist
	if has_site_include_file_for_404 "$domain" "443" && has_site_include_file_for_404 "$domain" "80"; then
		echo "  Per-site includes already exist for ${domain}; updating userdata files"
	else
		# Extract 404 block from existing userdata or .htaccess if site had one previously
		local cp_404_block=""
		local cp_from_htaccess="false"
		
		# Prefer .htaccess for comment preservation and precedence; proceed only if last 404 is CF
		if [ -f "$docroot/.htaccess" ] && last_404_is_cf "$docroot/.htaccess"; then
			cp_404_block=$(extract_404_block "$docroot/.htaccess" || true)
			if [ -n "$cp_404_block" ]; then
				echo "  Using 404 from .htaccess for cPanel per-site includes"
				cp_from_htaccess="true"
			fi
		fi
		
		# If still empty, try to find in existing userdata files
		if [ -z "$cp_404_block" ]; then
			for d in "${CPANEL_USERDATA_SSL_PATH}/${user}/${domain}" "${CPANEL_USERDATA_STD_PATH}/${user}/${domain}"; do
				[ -d "$d" ] || continue
				while IFS= read -r f; do
					[ -f "$f" ] || continue
					# Only proceed if the last 404 in this file is CF
					if last_404_is_cf "$f"; then
						cp_404_block=$(extract_404_block "$f" || true)
						if [ -n "$cp_404_block" ]; then
							echo "  Using 404 from userdata file: $f"
							break
						fi
					fi
				done < <(find "$d" -type f -maxdepth 1 2>/dev/null)
				if [ -n "$cp_404_block" ]; then
					break
				fi
			done
		fi
		
		# Generate per-site include files if we have a 404 block
		if [ -n "$cp_404_block" ]; then
			generate_site_404_include "$domain" "443" "$cp_404_block"
			generate_site_404_include "$domain" "80" "$cp_404_block"
			
			# Comment out original 404s after successful include generation
			if [ "$cp_from_htaccess" = "true" ]; then
				backup_file "$docroot/.htaccess"
				comment_all_404_lines "$docroot/.htaccess"
			fi
			
			# Comment out any pre-existing 404s in existing userdata files
			for d in "${CPANEL_USERDATA_SSL_PATH}/${user}/${domain}" "${CPANEL_USERDATA_STD_PATH}/${user}/${domain}"; do
				[ -d "$d" ] || continue
				while IFS= read -r f; do
					[ -f "$f" ] || continue
					if grep -qiE "$ANY404_REGEX" "$f"; then
						echo "  Commenting out pre-existing 404s in userdata file: $f"
						backup_file "$f"
						comment_all_404_lines "$f"
					fi
				done < <(find "$d" -type f -maxdepth 1 2>/dev/null)
			done
		fi
	fi
	
	# Create/update userdata files with includes
	local ssl_include="${SITE_INCLUDES_404_DIR}/${domain}-443.conf"
	local http_include="${SITE_INCLUDES_404_DIR}/${domain}-80.conf"
	
	# SSL userdata file
	backup_file ${CPANEL_USERDATA_SSL_PATH}/${user}/${domain}/lucee.conf
	cat > ${CPANEL_USERDATA_SSL_PATH}/${user}/${domain}/lucee.conf << EOF
# This file is automatically generated and managed by
# ${UPG_DIR}/configure-apache.sh
# Any manual changes will be overwritten when the script runs

Include /opt/lucee/sys/upgrade-in-progress/lucee-detect-upgrade.conf

EOF
	
	# Add per-site include if it exists
	if [ -f "$ssl_include" ]; then
		append_with_single_newline "Include $ssl_include" ${CPANEL_USERDATA_SSL_PATH}/${user}/${domain}/lucee.conf
	fi
	
	# Normalize whitespace
	normalize_conf_whitespace "${CPANEL_USERDATA_SSL_PATH}/${user}/${domain}/lucee.conf"
	
	# HTTP userdata file
	backup_file ${CPANEL_USERDATA_STD_PATH}/${user}/${domain}/lucee.conf
	cat > ${CPANEL_USERDATA_STD_PATH}/${user}/${domain}/lucee.conf << EOF
# This file is automatically generated and managed by
# ${UPG_DIR}/configure-apache.sh
# Any manual changes will be overwritten when the script runs

Include /opt/lucee/sys/upgrade-in-progress/lucee-detect-upgrade.conf

EOF
	
	# Add per-site include if it exists
	if [ -f "$http_include" ]; then
		append_with_single_newline "Include $http_include" ${CPANEL_USERDATA_STD_PATH}/${user}/${domain}/lucee.conf
	fi
	
	# Normalize whitespace
	normalize_conf_whitespace "${CPANEL_USERDATA_STD_PATH}/${user}/${domain}/lucee.conf"
}

# Function to configure RHEL sites
configure_site_redhat() {
	local domain=$1
	local docroot=$2

	echo "Processing site $domain with DocumentRoot: $docroot"

	# Copy lucee-upgrade-in-progress.html to DocumentRoot
	copy_upgrade_html "$docroot"

	# Locate SSL VirtualHost file containing ServerName and :443
	local ssl_conf_file=""
	for f in "${CONF_DIR}/*.conf" "${CONF_DIR}/httpd.conf"; do
		[ -f "$f" ] || continue
		if grep -q "ServerName $domain" "$f" 2>/dev/null; then
			if grep -Eq '<VirtualHost[^>]*:443' "$f" 2>/dev/null; then
				ssl_conf_file="$f"
				break
			fi
		fi
	done

	local ssl_404_block=""
	if [ -n "$ssl_conf_file" ]; then
		echo "  Updating $ssl_conf_file (SSL vhost)"
		
		# Check if per-site include already exists
		if has_site_include_file_for_404 "$domain" "443"; then
			echo "  Per-site include already exists for ${domain}:443; ensuring vhost includes it"
			add_include_404_to_vhost "$ssl_conf_file" "$domain" "443"
			ensure_include_detect_upgrade_in_vhost "$ssl_conf_file" "$domain" "443"
		else
			# Extract 404 block for per-site include generation
			local ssl_from_htaccess="false"
			
			# Prefer .htaccess (more specific)
			if [ -f "$docroot/.htaccess" ] && last_404_is_cf "$docroot/.htaccess"; then
				ssl_404_block=$(extract_404_block "$docroot/.htaccess" || true)
				if [ -n "$ssl_404_block" ]; then
					echo "  Using 404 from .htaccess for SSL per-site include"
					ssl_from_htaccess="true"
				fi
			fi
			
			# If .htaccess was already commented by a prior run, recover the 404 from it
			if [ -z "$ssl_404_block" ] && [ -f "$docroot/.htaccess" ] && grep -qi 'NOTE: ErrorDocument 404 moved' "$docroot/.htaccess"; then
				ssl_404_block=$(extract_404_block_allow_commented "$docroot/.htaccess" || true)
				if [ -n "$ssl_404_block" ]; then
					echo "  Recovered 404 from commented .htaccess for SSL per-site include"
					ssl_from_htaccess="true"
				fi
			fi
			
			# If no .htaccess 404, fallback to local vhost 404
			if [ -z "$ssl_404_block" ]; then
				if last_404_is_cf "$ssl_conf_file"; then
					ssl_404_block=$(extract_404_block "$ssl_conf_file" || true)
					if [ -n "$ssl_404_block" ]; then
						echo "  Using local 404 from SSL vhost for per-site include"
					fi
				fi
			fi
			
			# Generate per-site include file if we have a 404 block
			configure_site_includes "$domain" "443" "$ssl_conf_file" "$docroot" "$ssl_404_block" "$ssl_from_htaccess"
			
			# Ensure detection include is present
			ensure_include_detect_upgrade_in_vhost "$ssl_conf_file" "$domain" "443"
		fi
	else
		echo "  Warning: Could not find SSL VirtualHost for $domain"
	fi

	# Locate HTTP VirtualHost file containing ServerName and :80 (or lacking :443 when matching domain)
	local http_conf_file=""
	for f in "${CONF_DIR}/*.conf" "${CONF_DIR}/httpd.conf"; do
		[ -f "$f" ] || continue
		if grep -q "ServerName $domain" "$f" 2>/dev/null; then
			if grep -Eq '<VirtualHost[^>]*:80' "$f" 2>/dev/null || ! grep -Eq '<VirtualHost[^>]*:443' "$f" 2>/dev/null; then
				http_conf_file="$f"
				break
			fi
		fi
	done

	if [ -n "$http_conf_file" ]; then
		echo "  Updating $http_conf_file (HTTP vhost)"
		
		# Check if per-site include already exists
		if has_site_include_file_for_404 "$domain" "80"; then
			echo "  Per-site include already exists for ${domain}:80; ensuring vhost includes it"
			add_include_404_to_vhost "$http_conf_file" "$domain" "80"
			ensure_include_detect_upgrade_in_vhost "$http_conf_file" "$domain" "80"
		else
			# Extract 404 block for per-site include generation
			local http_404_block=""
			local http_from_htaccess="false"
			
			# If we already have SSL 404 block, reuse it for HTTP
			if [ -n "$ssl_404_block" ]; then
				echo "  Reusing 404 from SSL vhost for HTTP per-site include"
				http_404_block="$ssl_404_block"
			else
				# Extract from .htaccess or vhost as fallback
				if [ -f "$docroot/.htaccess" ] && last_404_is_cf "$docroot/.htaccess"; then
					http_404_block=$(extract_404_block "$docroot/.htaccess" || true)
					if [ -n "$http_404_block" ]; then
						echo "  Using 404 from .htaccess for HTTP per-site include"
						http_from_htaccess="true"
					fi
				fi
				
				# If .htaccess was already commented by a prior run, recover the 404 from it
				if [ -z "$http_404_block" ] && [ -f "$docroot/.htaccess" ] && grep -qi 'NOTE: ErrorDocument 404 moved' "$docroot/.htaccess"; then
					http_404_block=$(extract_404_block_allow_commented "$docroot/.htaccess" || true)
					if [ -n "$http_404_block" ]; then
						echo "  Recovered 404 from commented .htaccess for HTTP per-site include"
						http_from_htaccess="true"
					fi
				fi
				
				# If no .htaccess 404, fallback to local vhost 404
				if [ -z "$http_404_block" ]; then
					if last_404_is_cf "$http_conf_file"; then
						http_404_block=$(extract_404_block "$http_conf_file" || true)
						if [ -n "$http_404_block" ]; then
							echo "  Using local 404 from HTTP vhost for per-site include"
						fi
					fi
				fi
			fi
			
			# Generate per-site include file if we have a 404 block
			configure_site_includes "$domain" "80" "$http_conf_file" "$docroot" "$http_404_block" "$http_from_htaccess"
			
			# Ensure detection include is present
			ensure_include_detect_upgrade_in_vhost "$http_conf_file" "$domain" "80"
		fi
	else
		echo "  Info: No HTTP VirtualHost found for $domain"
	fi

	# Final normalization: if per-site includes exist and .htaccess still has any 404s, comment them out
	if [ -f "$docroot/.htaccess" ] && grep -qiE "$ANY404_REGEX" "$docroot/.htaccess"; then
		if has_site_include_file_for_404 "$domain" "443" || has_site_include_file_for_404 "$domain" "80"; then
			echo "  Commenting out 404 ErrorDocument in $docroot/.htaccess and adding note"
			backup_file "$docroot/.htaccess"
			comment_all_404_lines "$docroot/.htaccess"
		fi
	fi
}

# Function to process all sites from the configuration file
process_sites() {
	
	echo ""
	echo "Configuring Lucee sites for scripted 'Upgrade in Progress' notifications ..."

	local configure_func=$1
	
	# Get data from txt file
	while IFS= read -r line; do
		domain=$(echo "$line" | awk '{print $1}')
		docroot=$(echo "$line" | awk '{print $2}')
		$configure_func "$domain" "$docroot"
		
	done < $SITES_FILE
}

# MAIN SCRIPT EXECUTION

# Debian, Ubuntu, Pop!_OS, etc
if [ "$IS_DEBIAN" = true ]; then
	ensure_global_confs
	generate_allowed_ip_proxy_include || exit 1
	press_enter_to_continue
	process_sites configure_site_debian
	if ! apache_config_test; then
		echo "Apache test FAILED. Aborting reload. Please check configuration files."
		exit 1
	fi
	apache_reload
	
# has conf.d (Fedora, Red Hat, AlmaLinux, Rocky Linux, etc)
elif [ -n "$CONF_DIR" ]; then
	# cPanel
	if [ "$IS_CPANEL" = true ]; then
		ensure_global_confs
		generate_allowed_ip_proxy_include || exit 1
		press_enter_to_continue
		process_sites configure_site_cpanel
		echo "Rebuilding Apache configuration ..."
		/scripts/rebuildhttpdconf
		if ! apache_config_test; then
			echo "Apache test FAILED. Aborting restart. Please check configuration files."
			exit 1
		fi
		echo "Gracefully restarting httpd ..."
		/scripts/restartsrv_httpd --graceful
	
	# NOT cPanel
	else
		ensure_global_confs
		generate_allowed_ip_proxy_include || exit 1
		press_enter_to_continue
		process_sites configure_site_redhat
		if ! apache_config_test; then
			echo "Apache test FAILED. Aborting reload. Please check configuration files."
			exit 1
		fi
		apache_reload
	fi

else
	echo "Unsupported environment (Debian or RedHat family required)"
	exit 1
fi			
	
echo ""
echo "DONE!"
