#!/bin/bash

# Interactive menu for Lucee "Upgrade in Progress" toolkit
# Location (after deploy): /opt/lucee/sys/upgrade-in-progress/menu.sh

# Determine script directory and source shared env
SCRIPT_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
. "${SCRIPT_DIR}/ENVIRONMENT.sh"
. "${SCRIPT_DIR}/shared-functions.sh"

run_edit_exclusions() {
	ensure_default_exclusions_file
	${EDITOR:-nano} "$EXCLUSIONS_FILE"
}

run_get_sites() {
	clear
	"${UPG_DIR}/get-lucee-sites.sh"
	press_enter_to_continue
}

run_edit_sites() {
	if [ ! -f "${SITES_FILE}" ]; then
		print "\nSites file not found: ${SITES_FILE}\n\nRun 'Get Apache Site Data' first to generate it."
		return
	fi
	${EDITOR:-nano} "${SITES_FILE}"
}

run_edit_ip_allow() {
	local TXT_FILE="${UPG_DIR}/ip-allow.txt"
	local CONF_FILE="${HTTPD_LUCEE_ROOT}/ip-allow.conf"

	# start with localhost defaults
	if [ ! -f "${TXT_FILE}" ]; then
		printf "# commented lines are ignored\n127.0.0.1\n::1\n" | tee "${TXT_FILE}" >/dev/null
	fi

	# Let user edit the allow list
	${EDITOR:-nano} "${TXT_FILE}"

	clear

	# Build new conf from non-empty, non-comment lines
	TMP_CONF="$(mktemp)"
	{
		echo "# ========== DO NOT EDIT THIS FILE =========="
		echo "# Use the menu.sh script to modify this file."
		echo "# ==========================================="
		echo "<IfModule mod_setenvif.c>"
		# Read lines, strip leading/trailing whitespace, skip blanks and comments
		while IFS= read -r line; do
			# Trim leading/trailing whitespace
			trimmed="${line##*[![:space:]]}"
			trimmed="${line%%*[[:space:]]}"
			# Fallback simple trim if above results empty handling is odd
			if [ -z "$trimmed" ]; then
				trimmed="$line"
			fi
			# Skip empty lines
			if [ -z "$(echo "$trimmed" | sed -e 's/^\s\+//' -e 's/\s\+$//')" ]; then
				continue
			fi
			# Skip commented lines
			case "$trimmed" in
				\#*)
					continue
					;;
			esac
			ip="$trimmed"
			# Escape dots for regex in IPv4; leave colons as-is for IPv6
			esc_ip="$(echo "$ip" | sed 's/\./\\\./g')"
			printf "\tSetEnvIf Remote_Addr \"%s\" LUCEE_UPGRADE_BYPASS=1\n" "$esc_ip"
		done < "$TXT_FILE"
		echo "</IfModule>"
		echo ""
	} > "$TMP_CONF"

	# Determine if there were any allow rules generated (lines with SetEnvIf)
	if grep -q "SetEnvIf Remote_Addr" "$TMP_CONF"; then
		:
	# Rebuild with header and empty block to avoid stale rules
	else
		{
			echo "# ========== DO NOT EDIT THIS FILE =========="
			echo "# Use the menu.sh script to modify this file."
			echo "# ==========================================="
			echo "<IfModule mod_setenvif.c>"
			printf "\t# No IPs currently allowed to bypass upgrade\n"
			echo "</IfModule>"
		} > "$TMP_CONF"
	fi

	cp -f --no-preserve=all "$TMP_CONF" "$CONF_FILE"
	rm -f "$TMP_CONF"

	# Reload Apache (handles cPanel vs non-cPanel)
	if ! apache_reload; then
		echo "Warning: Apache reload may have failed; see messages above."
	fi

	press_enter_to_continue
}

run_configure_apache() {
	clear
	"${UPG_DIR}/configure-apache.sh"
}

run_discover_apache_configs() {
	clear
	"${UPG_DIR}/get-current-configs.sh"
}

run_begin() {
	clear
	"${UPG_DIR}/begin.sh"
}

run_end() {
	clear
	"${UPG_DIR}/end.sh"
}

while true; do
	clear
	echo "------------------------------------------"
	echo " 'Upgrade in Progress' for Lucee + Apache"
	if [ -e "/var/lucee-upgrade-in-progress" ]; then
		echo "Current Server Status: UPGRADE IN PROGRESS"
	else
		echo " Current Server Status: NORMAL OPERATIONS"
	fi
	echo " (based on /var/lucee-upgrade-in-progress)"
	echo "------------------------------------------"
	echo ""
	echo "s) Customize Site Search Exclusions (optional)"
	echo ""
	echo "g) Get Apache Site Data"
	echo ""
	echo "v) View/Edit Apache Site Data File"
	echo ""
	echo "c) Configure Apache (previews changes and prompts for confirmation)"
	echo ""
	echo "r) Apache Configuration Discovery Report"
	echo ""
	echo "i) IP Allow List (for QA Testing)"
	echo ""
	echo "b) Begin 'Upgrade in Progress'"
	echo ""
	echo "e) End 'Upgrade in Progress'"
	echo ""
	echo "q) Quit"
	echo ""
	read -r -p "Select an option: " choice
	case "${choice}" in
		s|S)
			run_edit_exclusions
			;;
		g|G)
			run_get_sites
			;;
		v|V)
			run_edit_sites
			;;
		c|C)
			run_configure_apache
			press_enter_to_continue
			;;
		r|R)
			run_discover_apache_configs
			press_enter_to_continue
			;;
		i|I)
			run_edit_ip_allow
			;;
		b|B)
			run_begin
			press_enter_to_continue
			;;
		e|E)
			run_end
			press_enter_to_continue
			;;
		q|Q)
			echo "Exiting."
			exit 0
			;;
		*)
			echo "Invalid selection."
			;;
	esac
done
